#!/bin/sh
#
# @name Gazebo x500 lidar 2d down
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_lidar_2d_down}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

echo "Disabling Sim GPS"
param set-default SYS_HAS_GPS 0
param set-default EKF2_EV_CTRL 9
param set-default EKF2_GPS_CTRL 0
